require: rubocop-rspec

AllCops:
  Exclude:
    - spec/spec_helper.rb
  DisplayCopNames: true
  DisplayStyleGuide: true

Lint/FormatParameterMismatch:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - spec/rubocop_spec.rb

RSpec/ExampleLength:
  Max: 8

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
